<html>
	<head>
		<title>Goon Squad | Home</title>
		<link rel="stylesheet" type="text/css" href="css/style.css"/>
	</head>
	<body>
	<!--This menu will probably be generated by PHP at some point.
	<div class="menu">
		<p class="link" mouseover="mouseOver()" mouseout="mouseOut()"><a href="index.php">Welcome</a><span id="rectangle"></span></p>
		<p class="link"><a href="index.php">Calendar</a><span id="rectangle"></span></p>
	</div>-->
	<?php include("php/menu.php")?>
	<div id="content">
	<span id="goon">Calendar</span>
	<br>
	<H2>Team 3604</H2>
	<br>
	 <iframe src="https://calendar.google.com/calendar/embed?mode=AGENDA&height=800&wkst=1&bgcolor=%23c0c0c0&src=whs.robotics.3604@gmail.com&color=%235229A3&ctz=America/New_York" width="100%" style="height:150%;"></iframe>
	
	</div>
	</body>
<script src = "js/highlightscript.js">
</script>
</html>