<!DOCTYPE html>
<html>
	<head>
		<title>Goon Squad | Contact</title>
		<link rel="stylesheet" type="text/css" href="stylesheetreset.css"/>
	    <link rel="stylesheet" type="text/css" href="stylesheet.css"/>
	</head>
	<body onload="toggleNav()">
	
	<script src="main.js"></script>
	  <nav id="nav-main">
	    <div id="btn-togle-nav" onclick="toggleNav()"></div>
		<img id="logo_top" src="img/logo2"></img>
		 <h1 id="GoonSquad">Goon Squad</h1>
	  </nav>
	  
	  <aside id="nav-sidebar">
	    <ul>
			<?php 
				include("php/menu.php");
			?>
		</ul>
	  </aside>
	<!--This menu will probably be generated by PHP at some point.
	<div class="menu">
		<p class="link" mouseover="mouseOver()" mouseout="mouseOut()"><a href="index.php">Welcome</a><span id="rectangle"></span></p>
		<p class="link"><a href="index.php">Calendar</a><span id="rectangle"></span></p>
	</div>-->
	<!--<?php include("php/menu.php")?>-->
	<div class="content">
	<span id="goon">Contact</span>
	<br>
	<H2 class="cal_goon">Team 3604</H2>
	<br>
	<H2 id="contact_us">Contact at: whs.robotics.3604@gmail.com</H2> <br>
If you would like to contact the Goon Squad, please send us an email! We will get back to you as soon as we can! If you do not receive a response within 72 hours, please just send another email.
	</div>
	<?php include("php/footer.php")?>
	</body>
<!--<script src = "js/highlightscript.js">
</script>-->
</html>