<!DOCTYPE>
<html>
	<head>
		<title>Goon Squad | Robots</title>
	    <link rel="stylesheet" type="text/css" href="stylesheet.css"/><link rel="stylesheet" type="text/css" href="stylesheetreset.css"/>
	    <link rel="stylesheet" type="text/css" href="stylesheet.css"/>
		</head>
		<body onload="toggleNav()">
		
		<script src="main.js"></script>
	  <nav id="nav-main"/>
	    <div id="btn-togle-nav" onclick="toggleNav()"></div>
		<img id="logo_top" src="img/logo_top.png"></img>
		 <h1 id="GoonSquad">Goon Squad</h1>
	  </nav>
	  
	  <aside id="nav-sidebar">
	    <ul>
			<?php 
				include("php/menu.php");
			?>
		</ul>
	  </aside>
	<!--This menu will probably be generated by PHP at some point.
	<div class="menu">
		<p class="link" mouseover="mouseOver()" mouseout="mouseOut()"><a href="index.php">Welcome</a><span id="rectangle"></span></p>
		<p class="link"><a href="index.php">Calendar</a><span id="rectangle"></span></p>
	</div>-->
	<!--<?php include("php/robots.php")?>-->
	<div class="content">
	<span id="goon">Robots</span>
	<br><br>
	<H2 class="cal_goon">Team 3604</H2>
	<br><br>
	<h3>Power Up 2018 Bot</h3>
	<br>
	<p>This bot won one blue banner, went to states, and went to worlds! It had the power to place power cubes anywhere and climb to great heights with its scissor lift to face the boss with ease.</p>
	<br>
	<img id="power_up_bot"src="img/powerup.jpg"></img>
	<br><br>
	<h3>Steamworks 2017 Bot</h3>
	<br>
	<p>This bot could steamroll the competition helping us make it to states this year with its velcro-based climbing mechanism and its gear holding mechanism. </p>
	<br>
	<img id="steam_works" src="img/SteamWorks.JPG"></img>
	<br><br>
	<h3>Stronghold 2016 Bot</h3>
	<br>
	<p>In this season, our climber was ranked number one in Michigan. We traverse through defenses without problems. We Launch boulders with ease at the high and low goal. This bot took us to worlds and we became the second pick of the 8th alliance on the Hopper field. along the way we received two blue banners, one from Southfield, and our home event Woodhaven.</p>
	<br>
	<img id="Stronghold" src="img/ROBOT2.JPG"></img>
	<br><br>
	<h3>Recycle Rush 2015 Bot</h3>
	<br>
	<p> During this season we had a dual sided robot the could stack totes six high and top it off with a recycling container. We won our first blue banner ever at our home event Woodhaven. We also qualified for states and worlds this year, but we did not do much. </p>
	<br>
	<img id="Recycle_rush" src="img/RecycleRush.jpg"></img>
	<br><br>
	<h3>Aerial Assist 2014 Bot</h3>
	<br>
	<p> This season we made it to states we did not make it to worlds by two seats sadly. we made it to the finals in both of our qualifying events. We used a Catapult to launch the exercise balls high. We had just about everything on our robot, so overall it was a decent season. </p>
	<br>
	<img id="Aerial_Assist" src= "img/aerial_assist.jpg"></img>
	<br><br>
	<h3>Ultimate Ascent 2013 Bot</h3>
	<br>
	<p> During this season it was our first time making it to finals at a district, and being a captain. Also the first year we made it to states. We shoot full field Frisbees shoots at the third level goal. </p>
	<br>
	<img id ="Ultimate_ascent" src="img/Ultimate_ascent.PNG"></img>
	<br><br>
	<h3> Rebound Rumble 2012 Bot</h3>
	<br>
	<p>We shot basketballs. That is it, nothing else.</p>
	<br>
	<img id="rebound_rumble"src="img/Rebound_Rumble2012.PNG"></img>
	<br><br>
	<h3> Logo Motion 2011 Bot </h3>
	<br>
	<p> We had a mini bot, and we could make it up to the second peg. We made it to semi-finals in our second event Waterford. </p>
	<br>
	<img id="LogoMotion"src="img/2011Logomotion.PNG"></img>
	
	</div>
	<?php include("php/footer.php")?>
	</body>
</html>