<html>
	<head>
		<title>Goon Squad | Home</title>
		<link rel="stylesheet" type="text/css" href="css/style.css"/>
	</head>
	<body>
	<!--This menu will probably be generated by PHP at some point.
	<div class="menu">
		<p class="link" mouseover="mouseOver()" mouseout="mouseOut()"><a href="index.php">Welcome</a><span id="rectangle"></span></p>
		<p class="link"><a href="index.php">Calendar</a><span id="rectangle"></span></p>
	</div>-->
	<?php include("php/menu.php")?>
	<div id="content">
	<span id="goon">Safety</span>
	<br>
	<H2>Team 3604</H2>
	<br>
	</div>
	</body>
<script src = "js/highlightscript.js">
</script>
</html>