<!DOCTYPE html>
<html>
	<head>
		<title>Goon Squad | Safety</title>
		<link rel="stylesheet" type="text/css" href="stylesheetreset.css"/>
	    <link rel="stylesheet" type="text/css" href="stylesheet.css"/>
	</head>
	<body onload="toggleNav()">
	
	<script src="main.js"></script>
	  <nav id="nav-main"/>
	    <div id="btn-togle-nav" onclick="toggleNav()"></div>
		<img id="logo_top" src="img/logo_top.png"></img>
		 <h1 id="GoonSquad">Goon Squad</h1>
	  </nav>
	  
	  <aside id="nav-sidebar">
	    <ul>
			<?php 
				include("php/menu.php");
			?>
		</ul>
	  </aside>
	<!--This menu will probably be generated by PHP at some point.
	<div class="menu">
		<p class="link" mouseover="mouseOver()" mouseout="mouseOut()"><a href="index.php">Welcome</a><span id="rectangle"></span></p>
		<p class="link"><a href="index.php">Calendar</a><span id="rectangle"></span></p>
	</div>-->
	<!--<?php include("php/menu.php")?>-->
	<div class="content">
	<span id="goon">Safety</span>
	<br>
	<br>
	<H2 class="cal_goon">Team 3604</H2>
	<br>
	<p>In the shop, one of the most important things is safety. Without safety, people would be losing limbs left, right, and center. That is why the Goon Squad comes prepared with a plethora of safety equipment, and two highly trained safety captains that know how to use it all. Additionally, everyone on the team is trained, and certified in CPR (cardiopulmonary resuscitation), and AED (Automated External Defibrillator) in case someone ever becomes unresponsive, or pases out. Our safety captains insure our safety by providing us with evacuation plans in case of a emergency and treat simple cuts, and bruises that we may get in the shop to make sure they do not get infected later. 
We have two safety captains; one being a veteran with 3 years of past experience, and the other being a rookie with it being their first year. Our lead safety captain won three URL safety stars in last years game two at qualifying events and one at worlds! The safety captains keep a log of all of the past injuries in our shop, to prove how safe we actually are. In conclusion, safety is one of the main priorities in our shop, and that is thanks to our great safety captains.

</p>
	</div>
	<?php include("php/footer.php")?>
	</body>
<!--<script src = "js/highlightscript.js">
</script>-->
</html>