<!DOCTYPE html>
 <html>
	<head>
		<title>Goon Squad | Sponsors</title>
	<link rel="stylesheet" type="text/css" href="stylesheetreset.css"/>
	<link rel="stylesheet" type="text/css" href="stylesheet.css"/>
	<!--<script src="main.js"></script>-->
	</head>
	<body onload="toggleNav()">
	
	<script src="main.js"></script>
	  <nav id="nav-main"/>
	    <div id="btn-togle-nav" onclick="toggleNav()"></div>
		<img id="logo_top" src="img/logo_top.png"></img>
		 <h1 id="GoonSquad">Goon Squad</h1>
	  </nav>
	  
	  <aside id="nav-sidebar">
	    <ul>
			<?php 
				include("php/menu.php");
			?>
		</ul>
	  </aside>
	<!--This menu will probably be generated by PHP at some point.
	<div class="menu">
		<p class="link" mouseover="mouseOver()" mouseout="mouseOut()"><a href="index.php">Welcome</a><span id="rectangle"></span></p>
		<p class="link"><a href="index.php">Calendar</a><span id="rectangle"></span></p>
	</div>-->
	<!--<?php include("php/menu.php")?>-->
	<div class="content">
	<span id="goon">Sponsors</span>
	<br>
	<H2 class="cal_goon">Team 3604</H2>
	<br>
	</td><td>Visit our great sponsors!</td></tr></table><br><br>
		 <a href="http://gm.com"><img src="img/gm.png" height="64px"></a>&nbsp &nbsp &nbsp
		 <a href="http://ford.com"><img src="img/ford.png" height="64px"></a>&nbsp &nbsp &nbsp
		<a href="http://mcdonalds.com"><img src="img/mcdonalds.png" height="64px"></a>&nbsp &nbsp &nbsp
		<a href="http://tedsonindustries.com"><img src="img/tedson.jpg" height="64px"></a>&nbsp &nbsp &nbsp
		<a href="http://icrservices.com"><img src="img/icr.png" height="64px"></a>&nbsp &nbsp &nbsp
		<a href="http://rcoeng.com"><img src="img/rco.png" height="64px"></a>&nbsp &nbsp &nbsp
		<a href="http://searchplusinternational.com/"><img src="img/searchplus.png" height="64px"></a>&nbsp &nbsp &nbsp
		<!--<a <img src="img/dadara.jpg" height="128px">&nbsp &nbsp &nbsp-->
		<a href="http://www.local387.org/"><img src="img/uaw.png" height="64px"></a>&nbsp &nbsp &nbsp
		<a href="http://region1a.uaw.org/local600/"><img src="img/uaw2.png" height="64px"></a>&nbsp &nbsp &nbsp
		<a href="http://wbsd.co"><img src="img/wbsd.png" height="64px"></a>&nbsp &nbsp &nbsp
		<img src="img/dadara.png" height="64px">&nbsp &nbsp &nbsp
		<a href="https://www.texasroadhouse.com/" style="text-decoration: none;"><img src="img/texasRoadhouse.png" height="64px"></a>&nbsp &nbsp &nbsp
		<!--<a href="http://www.nvidia.com/content/global/global.php"><img src="img/nvidia-logo.png" height="64px"></a>&nbsp &nbsp &nbsp-->
		<a href="http://bestbuy.com/"><img src="img/bestbuy.png" height="64px"></a>&nbsp &nbsp &nbsp
		<a href="http://www.valiantcorp.com/"><img src="img/valiant.png" height="64px"></a>&nbsp &nbsp &nbsp
		<a href="https://www.fcagroup.com/en-US/Pages/home.aspx"><img src="img\fca.png" height="64px"></a>&nbsp &nbsp &nbsp
		<span style="font-size: 64px; font-weight: bold;">IICC</span>

		<a href="https://megs.mde.state.mi.us/megs/" style="color: white; text-decoration: none; font-family: Sans-serif;">
		<img src="img/MEG.png" height="64px">&nbsp &nbsp &nbsp\
		
		<span style="color:black">Michigan Educational Grant</a><br>
		</a>
		</a>
	</div>
	<?php include("php/footer.php")?>
	</body>
<!--<script src = "js/highlightscript.js">
</script>-->
</html>