<html>
	<head>
		<title>Goon Squad | Contact</title>
		<link rel="stylesheet" type="text/css" href="css/style.css"/>
	</head>
	<body>
	<!--This menu will probably be generated by PHP at some point.
	<div class="menu">
		<p class="link" mouseover="mouseOver()" mouseout="mouseOut()"><a href="index.php">Welcome</a><span id="rectangle"></span></p>
		<p class="link"><a href="index.php">Calendar</a><span id="rectangle"></span></p>
	</div>-->
	<?php include("php/menu.php")?>
	<div id="content">
	<span id="goon">Contact</span>
	<span class="cal_goon">Team 3604</span>
	<br>
	<H2>Contact at: whs.robotics.3604@gmail.com</H2>
If you would like to contact the Goon Squad, please send us an email! We will get back to you as soon as we can! If you do not receive a response within 72 hours, please just send another email.
	</div>
	<?php include("php/footer.php")?>
	</body>
<script src = "js/highlightscript.js">
</script>
</html>