<html>
	<head>
		<title>Goon Squad | Home</title>
		<link rel="stylesheet" type="text/css" href="css/style.css"/>
	</head>
	<body>
	<!--This menu will probably be generated by PHP at some point.
	<div class="menu">
		<p class="link" mouseover="mouseOver()" mouseout="mouseOut()"><a href="index.php">Welcome</a><span id="rectangle"></span></p>
		<p class="link"><a href="index.php">Calendar</a><span id="rectangle"></span></p>
	</div>-->
	<?php include("php/menu.php")?>
	<div id="content">
	<span id="goon">GOON SQUAD</span>
	<span style="float: right; font-size: 36pt; font-weight: bold; margin-top: 14px;">Team 3604</span>
	<p style="margin-top: 6px;">We are the Goon Squad, Team 3604. We are an FRC Robotics Team for Woodhaven High School / Woodhaven-Brownstown School District. We have been a team for 7 years and running, with many great sponsors and mentors supporting us along the way! Our school is located on Van Horn Rd in <strong>Brownstown, Michigan.</strong> </p>
	<!--<p>We are the Goon Squad, Team 3604. We are an FRC Robotics Team for Woodhaven High School / Woodhaven-Brownstown School District. We have been a team for 7 years and running, with many great sponsors and mentors supporting us along the way! Our school is located on Van Horn Rd in <strong>Brownstown, Michigan.</strong></p>-->
	
	<!--<video id="homepageVideo">
        <source src="img/video.mp4" type="video/mp4"/>
        </video>-->
        <br>
        <!--<h1>Visit Our Social Media!</h1>
	<a style="text-decoration: none;" href="https://www.facebook.com/pages/Woodhaven-Robotics-Team-3604/167378876696706">
	<img src="img/facebook.png" height="10%">
	 </a>
	 <a style="text-decoration: none;" href="https://twitter.com/GoonSquad3604">
	<img src="img/twitter.png" height="10%">
		</a>
	 <a style="text-decoration: none;" href="http://www.youtube.com/user/WhsRobotics3604?feature=watch">
	<img src="img/youtube.png" height="10%">
		</a>
			 
		<br>-->
		<!--
		<center> <!--:: TODO :: Replace these janky center tags with something better!
		<img src="img/homepage_images/img0.png" id="slideshow"/>
			
		</center>
		<p id="slideshowkebobs">
				<span onclick="changeImage('img/homepage_images/img0.png')" class="kebob"> o </span>
				<span onclick="changeImage('img/homepage_images/img1.png')" class="kebob"> o </span>
				<span onclick="changeImage('img/homepage_images/img2.png')" class="kebob"> o </span>
			</p>-->
		<h1>Visit These Links!</h1>
<br>
		<a style="text-decoration: none;" href="http://wbsd.co">
		<img src="img/wbsd.png" height="10%">
		</a>
		<a style="text-decoration: none;" href="http://firstinspires.org">
		<img src="img/firstlogo.png" height="10%">
		</a>
		<a style="text-decoration: none;" href="http://firstinmichigan.org">
	 <img src="img/firstinmichigan.png" height="10%">
	 </a>	
	</div>
	<?php include("php/footer.php")?>
<script src = "js/highlightscript.js">
</script>
<script src = "js/images.js">
</script>
</html>