<html>
	<head>
		<title>Goon Squad | Safety</title>
		<link rel="stylesheet" type="text/css" href="css/style.css"/>
	</head>
	<body>
	<!--This menu will probably be generated by PHP at some point.
	<div class="menu">
		<p class="link" mouseover="mouseOver()" mouseout="mouseOut()"><a href="index.php">Welcome</a><span id="rectangle"></span></p>
		<p class="link"><a href="index.php">Calendar</a><span id="rectangle"></span></p>
	</div>-->
	<?php include("php/menu.php")?>
	<div id="content">
	<span id="goon">Safety</span>
	<span class="cal_goon">Team 3604</span>
	<?php include("content/safety.php");?>
	</div>
	<?php include("php/footer.php")?>
	</body>
<script src = "js/highlightscript.js">
</script>
</html>